import os


def convert_file(in_file_name, out_file_name):
    with open(in_file_name, 'rb') as f:
        with open(out_file_name, 'w') as f2:
            f2.write("// This file is auto-generated by convert.py. Do not modify.\n");
            f2.write("pub fn get_bytecode() -> @Array<u8> {\n    @array![");
            byte = f.read(1)
            while byte:
                f2.write('0x{:02x},'.format(ord(byte)))
                byte = f.read(1)
            f2.write(']\n}\n')
    print('  Converted', in_file_name, 'to', out_file_name)

def main():
    convert_file(os.path.join('guest_rs', 'target', 'riscv32i-unknown-none-elf', 'release', 'riscairo_guest_rs'), os.path.join('host_cairo', 'src', 'guest_rs_bytecode.cairo'))


if __name__ == '__main__':
    main()
