[package]
name = "host_cairo"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
riscairo = { path = "../riscairo" }
starknet = ">=2.3.0"
# add your dependencies here

[dev-dependencies]
cairo_test = "2.8.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }

[[target.starknet-contract]]
sierra = true # Enable Sierra codegen.
casm = true   # Enable Casm codegen.
