[package]
name = "host_cairo"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
riscairo = { git = "https://github.com/massalabs/riscairo.git", branch = "update_version" }
starknet = ">=2.3.0"

[[target.starknet-contract]]
sierra = true        # Enable Sierra codegen.
