[package]
name = "riscv"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "scarb-riscv"
path = "src/main.rs"

[dev-dependencies]
sha2 = "0.10.8"
hex-literal = "0.4.1"
rustc-hex = "2.1.0"
tempfile = "3.3.0"